### ISSUE TITLE
Firestore in Datastore mode

### ISSUE THREAD

**Issue by hotyes** [mrbandler/FsFirestore#2]
Hi @mrbandler 

great works, btw .. do you have any plan to support firestore in datastore mode?

https://cloud.google.com/datastore/docs/firestore-or-datastore#in_datastore_mode

Thanks

**Comment by mrbandler** [comment]
Hey there @hotyes,

Did not know about this, but I will look into it and get back to you.

**Comment by mrbandler** [comment]
Soo, I got familiar with the topic.

And as I understand it it's nothing that I can implement this is a setting you can choose on your database instance on your Firebase project.

This *datastore* mode is just a backward compatibility option for existing applications that use Cloud Datastore to upgrade to the newer underlying Cloud Firestore storage layer but keep the same API in place with some removal of pre-existing limitations. Correct me if I am reading this wrong.

> **Quote:** Cloud Firestore can operate in Datastore mode, making it backwards- compatible with Cloud Datastore.

**See:** https://cloud.google.com/datastore/docs/upgrade-to-firestore

> **Quote:** 
Datastore mode disables Cloud Firestore features that are not compatible with Cloud Datastore:
- The project will accept Cloud Datastore API requests and deny Cloud Firestore API requests.
- The project will use Cloud Datastore indexes instead of Cloud Firestore indexes.
- **You can use Cloud Datastore client libraries with this project but not Cloud Firestore client libraries.**
- Cloud Firestore real-time capabilities will not be available.
- In the GCP Console, the database will use the Cloud Datastore viewer.

**See:** https://cloud.google.com/datastore/docs/firestore-or-datastore#in_datastore_mode

---

As this library is only to be used with the Firestore API, I can not provide or implement this feature. If you plan to upgrade your DB to a Firestore DB without *datastore* mode enabled you can use FsFirestore.
I'd recommend this approach as Firestore has so much more in store (pun intended) then Datastore.

Sorry for not being more helpful here, it looks as I would need to implement a Cloud Datastore F# wrapper too. 😅
